# Generated by Django 4.1.4 on 2023-02-12 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('telephone', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=10)),
                ('carreer', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('net', models.IntegerField(default=0)),
                ('property', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('gc_name', models.CharField(max_length=100)),
                ('desc', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2023, 2, 12))),
                ('status', models.CharField(default='Start', max_length=100)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('goods', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.goods')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.order')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodscategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.goodscategory'),
        ),
    ]
